################################################################################
# pipeline.R — Pseudobulk DESeq2 Pipeline
#
# Performs pseudobulk DEG analysis from a Seurat object using muscat for
# aggregation and DESeq2 for differential expression. Supports optional SVA
# for hidden confounder correction and both numeric and categorical primary
# variables.
#
# Steps:
#   1. Pseudobulk aggregation (muscat)
#   2. Per-cell-type DESeq2 with optional SVA
#   3. Summary plots and result tables
#
# Usage:
#   Rscript pipeline.R config.R
#
# SVA note:
#   When USE_SVA = TRUE, surrogate variables are added as covariates to the
#   DESeq2 design formula. Raw counts are always used as DESeq2 input —
#   counts are NEVER modified by SVA. SVA-corrected values (via
#   removeBatchEffect) are computed only for MDS/PCA/heatmap visualization.
#
# Do NOT edit this file. Edit config.R only.
################################################################################

options(stringsAsFactors = FALSE)

# ── Load config ───────────────────────────────────────────────────────────────

args        <- commandArgs(trailingOnly = TRUE)
config_file <- if (length(args) >= 1) args[1] else "config.R"

if (!file.exists(config_file))
  stop("Config file not found: ", config_file,
       "\nUsage: Rscript pipeline.R config.R")

source(config_file)
message("Loaded config from: ", config_file)

# ── Load sample metadata ──────────────────────────────────────────────────────

if (!file.exists(SAMPLE_METADATA_FILE))
  stop("Sample metadata file not found: ", SAMPLE_METADATA_FILE)

sep             <- if (grepl("\\.tsv$", SAMPLE_METADATA_FILE, ignore.case = TRUE)) "\t" else ","
sample_metadata <- read.table(SAMPLE_METADATA_FILE, header = TRUE, sep = sep,
                               stringsAsFactors = FALSE, check.names = FALSE)

if (!"sample_id" %in% colnames(sample_metadata))
  stop("sample_metadata must contain a 'sample_id' column.")

rownames(sample_metadata) <- sample_metadata$sample_id

# Validate required columns
required_cols <- c(names(BIO_VARS), COVARIATES)
missing_cols  <- setdiff(required_cols, colnames(sample_metadata))
if (length(missing_cols) > 0)
  stop("Metadata missing required columns: ", paste(missing_cols, collapse = ", "))

message("Loaded metadata: ", nrow(sample_metadata), " samples, ",
        ncol(sample_metadata) - 1, " variables")
message("Sample IDs in metadata: ", paste(sort(sample_metadata$sample_id), collapse = ", "))

# ── Source modules ────────────────────────────────────────────────────────────

module_dir <- file.path(dirname(normalizePath(config_file)), "modules")
if (!dir.exists(module_dir)) module_dir <- "modules"

for (mod in c("check_packages.R", "utils.R", "pseudobulk.R",
              "deseq2_analysis.R", "summary_plots.R")) {
  path <- file.path(module_dir, mod)
  if (!file.exists(path))
    stop("Module not found: ", path)
  source(path)
}

check_and_install_packages()

# ── Create output directories ─────────────────────────────────────────────────

subdirs <- c("DESeq2_results", "Heatmaps", "MDS_Plots", "PCA_Plots", "Summary")
for (d in subdirs)
  dir.create(file.path(OUTPUT_DIR, d), recursive = TRUE, showWarnings = FALSE)

message("Output directory: ", OUTPUT_DIR)

# ── Echo config ───────────────────────────────────────────────────────────────

message("\n── Analysis configuration ───────────────────────────────────────────────────")
message("  Biological variables:")
for (var in names(BIO_VARS)) {
  spec <- BIO_VARS[[var]]
  info <- if (spec$type == "categorical")
            paste0("categorical (ref = '", spec$reference, "')")
          else "numeric"
  message("    ", var, " — ", info)
}
message("  Technical covariates : ",
        if (length(COVARIATES) > 0) paste(COVARIATES, collapse = ", ") else "none")
message("  SVA                  : ",
        if (USE_SVA) paste0("yes (method = '", SVA_METHOD, "')") else "no")
message("  FDR threshold        : ", FDR_THRESHOLD)

# ── Pipeline start ────────────────────────────────────────────────────────────

pipeline_start <- proc.time()
message("\nPipeline started: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n")

################################################################################
# STEP 1: Pseudobulk aggregation
################################################################################

t1_start  <- proc.time()
pb_result <- run_pseudobulk()
t1_end    <- proc.time()

################################################################################
# STEP 2: DESeq2 analysis (with optional SVA)
################################################################################

t2_start    <- proc.time()
deg_results <- run_deseq2_analysis(pb_result$counts_pb, sample_metadata)
t2_end      <- proc.time()

# Save outputs — save() requires plain variable names, not $ expressions
vst_counts    <- deg_results$vst_counts
deseq_results <- deg_results$deseq_results

saveRDS(vst_counts,    file = stamp_dir("DESeq2_results", "PB_VST_counts",    ext = "rds"))
saveRDS(deseq_results, file = stamp_dir("DESeq2_results", "PB_DESeq2_results", ext = "rds"))

################################################################################
# STEP 3: Summary plots and tables
################################################################################

t3_start <- proc.time()
run_summary_plots(deg_results$deseq_results)
t3_end   <- proc.time()

################################################################################
# Timing summary
################################################################################

fmt_step <- function(s, e) {
  secs <- round((e - s)[["elapsed"]])
  sprintf("%02d:%02d:%02d", secs %/% 3600, (secs %% 3600) %/% 60, secs %% 60)
}
total_secs <- round((proc.time() - pipeline_start)[["elapsed"]])
total_hms  <- sprintf("%02d:%02d:%02d",
                      total_secs %/% 3600, (total_secs %% 3600) %/% 60, total_secs %% 60)

message("\n════════════════════════════════════════")
message("  Timing summary (hh:mm:ss)")
message("════════════════════════════════════════")
message(sprintf("  %-30s %s", "1: Pseudobulk aggregation", fmt_step(t1_start, t1_end)))
message(sprintf("  %-30s %s", "2: DESeq2 analysis",        fmt_step(t2_start, t2_end)))
message(sprintf("  %-30s %s", "3: Summary plots",          fmt_step(t3_start, t3_end)))
message("────────────────────────────────────────")
message(sprintf("  %-30s %s", "Total", total_hms))
message("════════════════════════════════════════\n")

################################################################################
# Session info
################################################################################

sink(stamp("session_info", ext = "txt"))
sessionInfo()
sink()

message("Pipeline complete: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"))
